name: Test SAIST Action

on:
  push:
    branches: [ main ]
    paths: 
      - '.github/actions/saist-scanner/**'
  pull_request:
    paths:
      - '.github/actions/saist-scanner/**'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Test Action
        uses: ./.github/actions/saist-scanner
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          scan-mode: 'full'
          fail-on-high: 'false'  # Don't fail tests
          